export {
  ALGORITHMS,
  ALGORITHM_IDS,
  DEFAULT_DITHER_OPTIONS,
  PALETTE_PRESETS,
  createPixelBuffer,
  createRng,
  dither,
  ditherImageData,
  downsampleBuffer,
  extractPalette,
  hexToRgb,
  isAlgorithmId,
  mergeDitherOptions,
  processBuffer,
  parsePalette,
  rgbToHex,
  upscaleNearest,
  type AlgorithmId,
  type AlgorithmMeta,
  type DitherOptions,
  type PixelBuffer,
  type Rgb,
} from './lib/dither.ts'

export {
  ditherBase64,
  ditherBatch,
  ditherBuffer,
  ditherFile,
  type ProcessFileOptions,
  type ProcessResult,
} from './lib/node.ts'
